config/routes.rb
Momwebsite::Application.routes.draw do
  resources :microposts

  root :to => 'static_pages#home'
  get "family" => "static_pages#family"
  get "guestbook" => "microposts#new"
  resources :microposts

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :city, :content, :state, :name, :email, :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SimpleCaptcha::ControllerHelpers
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.json
  def new
    @posts = Micropost.order("created_at DESC").all
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.json
  def create
    if simple_captcha_valid?
      @micropost = Micropost.new(params[:micropost])
    else
      format.html { render action: "/guestbook", notice: 'Captcha was incorrect.' }
    end

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to "/guestbook", notice: 'Micropost was successfully created.' }
        format.json { render json: "/guestbook", status: :created, location: @micropost }
      else
        format.html { render action: "/guestbook" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.json

  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def family
  end

  def guestbook
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<hr>
<div id="footer">
	<p class="text-muted credit">Made with love by <a href="http://www.iamwillpatrick.com">Will Patrick</a>. Contact Will at <%= link_to "wgpatrick@gmail.com", "mailto:wgpatrick@gmail.com" %> </p>
</div>

app/views/layouts/_header.html.erb
<div class="header">
	<ul class="nav nav-pills pull-right">
		<li> <%= link_to "Home", root_path %> 
		</li>
		<li><%= link_to "About Meg", family_path %>
		</li>
		<li><%= link_to "Guestbook", guestbook_path %> </p>
		</li>
	</ul>
	<h1>Memories of Meg</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Memories of Meg</title>
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
  <script src="/assets/galleria.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= render	'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/footer' %>
</div>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function(){
    $("a[rel^='prettyPhoto']").prettyPhoto({
    	social_tools:'',
    	default_width: 500,
    	allow_resize: false,
    	theme: 'light_rounded'
    	});
  });
</script>

</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div style="font-size:20px">
    <div class="field" >
      Name<br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      Message<br />
      <%= f.text_area :message, :class => 'style-message' %>
    </div>
    <div class="field">
      Email<br />
      <%= f.text_field :email %>
    </div>
    <%= show_simple_captcha %>
    <div class="actions">
      <%= f.submit "Write" %>
    </div>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Email</th>
    <th>City</th>
    <th>State</th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <!-- need to design this -->
  <tr>
    <td><%= micropost.name %></td>
    <td><%= micropost.content %></td>
    <td><%= micropost.email %></td>
    <td><%= micropost.city %></td>
    <td><%= micropost.state %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<div class="row">
	<div class="col-md-12">

	<p>We would love to hear your memories and thoughts about Meg. </p>
	<p>Please share them in the form below and they will be posted below.</p>

	<%= render 'form' %>

	<hr>
	<h3>Your memories of Meg:</h3>
	<hr>
	<% @posts.each do |micropost| %>
	<!-- need to design this -->

	 <div class="row">
	 	<div class='col-md-12' style='color:black'>
	 		<div class="row" style="margin-top:10px">
				<div class="col-md-5">
					<span style='font-weight:bold;font-size:20px;color:#333'><%= micropost.name %></span>
				</div>
				<div class='col-md-3 col-md-offset-4'>
					Posted on <%= micropost.created_at.strftime("%m/%d/%y") %>
				</div>
			</div>
			<div class="row">
				<div class='col-md-12'>
					<span style='font-size:20px;line-height:30px'><%= micropost.message %></span>
				</div>
			</div>
		</div>
	  </div>
	  <hr>
	<% end %>
	
	</div>
</div

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>City:</b>
  <%= @micropost.city %>
</p>

<p>
  <b>State:</b>
  <%= @micropost.state %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/simple_captcha/_simple_captcha.erb
<style type="text/CSS">
  .simple_captcha{border: 1px solid #ccc; padding: 5px !important;}
  .simple_captcha,
  .simple_captcha div{display: table;}
  .simple_captcha .simple_captcha_field,
  .simple_captcha .simple_captcha_image{
    border: 1px solid #ccc;
    margin: 0px 0px 2px 0px !important;
    padding: 0px !important;
  }
  .simple_captcha .simple_captcha_image img{
    margin: 0px !important;
    padding: 0px !important;
    width: 110px !important;
  }
  .simple_captcha .simple_captcha_label{font-size: 12px;}
  .simple_captcha .simple_captcha_field input{
    width: 150px !important;
    font-size: 16px;
    border: none;
    background-color: #efefef;
  }
</style>

<div class='simple_captcha'>
  <div class='simple_captcha_image'>
    <%= simple_captcha_options[:image] %>
  </div>
  
  <div class='simple_captcha_field'>
    <%= simple_captcha_options[:field] %>
  </div>
  
  <div class='simple_captcha_label'>
    <%= simple_captcha_options[:label] %>
  </div>
</div>

app/views/static_pages/family.html.erb
<h3>Margaret Graham Kemper</h3>
<h4>November 7, 1950 – December 4, 2013</h4>
<p>Written by Susan Patrick with help from Michael and Will.</p>
<p>Margaret “Meg” Graham Kemper, a loving wife, mother, aunt, and friend who fully embraced the gifts of life, passed away on Wednesday, December 4th at the age of 63.  She bravely faced cancer for the past six and half years and will forever remain a source of warmth and strength to all who knew her. She died at home surrounded by her husband and two children. </p>
<p>Meg was born on November 7, 1950 in Harrisonburg, Virginia and was raised on her family’s farm in the Shenandoah Valley.  As the youngest of three children, Meg was lovingly called “runt” by her father.  Quite the tomboy, Meg loved to help her father with work on the farm and always enjoyed games, sports, and being outside.  Her early years instilled a love of the outdoors that would remain a very important part of her life.</p>
<p>After graduating from Montevideo High School in Penn Laird, Virginia, Meg attended Westhampton College at the University of Richmond. After dabbling with Physical Education and Math majors, she discovered her interest in psychology and how well it complimented her innate and genuine interest in understanding and helping people. She graduated from Westhampton in 1973 with a degree in Psychology, earned a graduate degree in School Psychology from the University of North Carolina in 1975, and completed a Ph.D. in Counseling Psychology from Duke University in 1980.</p>
<p>Meg spent the next 32 years working as an individual therapist in private practice and with the Counseling and Psychology Services at the University of North Carolina at Greensboro and the University of North Carolina at Chapel Hill. In her early career, Meg was very involved in the Orange County Rape Crisis Center and was very committed to working with women who have experienced trauma. Throughout her years of practice as a psychologist, Meg valued the many relationships she built with her clients and cherished the opportunity to support others.</p>
<p>Meg met her husband, Michael Patrick, at a party in Chapel Hill in 1977. She asked Michael to dance and they soon became inseparable. In their early years as a couple, Meg and Michael enjoyed camping and hiking in the mountains. Meg and Michael married at Chapel of the Cross in Chapel Hill in 1981. They had the opportunity to travel widely in the United States and especially enjoyed visiting National Parks. Their daughter, Susan, was born in 1985 and their son, Will, was born in 1988. Shortly before her death, Meg said that her happiest moments were raising her children and then watching them grow into adults.</p> 
<p>Meg was very involved with Family Preschool, school PTAs, Girl Scouts, and her children’s many activities.  She believed strongly in the importance of being physically and mentally present for those that she loved. She showed her love through cheering for countless hours of rec league sports and horse shows, organizing annual trips to Sunset Beach and the North Carolina mountains, and leading her family in silly and serious traditions.  After her cancer diagnosis, Meg felt strongly about upholding these family traditions and also seized the opportunity to make multiple trips to Europe and the Caribbean with her family.</p>
<p>Meg loved being active, spending time outdoors, reading, baking, and gardening. An athlete since childhood, she started running in college and was training for a marathon when she was diagnosed with cancer in 2007. Her competitive spirit came out while spending many years shooting hoops with her son or playing rousing board and card games with her family. She loved biking and running on the beaches of North and South Carolina and hiking along the Blue Ridge Parkway.</p>
<p>Closer to home, Meg treasured her daily walks along the section of Morgan Creek running behind her family’s home. She loved to read and often shared her reading recommendations and reflections on novels with her daughter and the many different book clubs that she attended through the years. Meg became an avid gardener and took great care in tending the many plants, trees, and flowers around her home.</p>
<p>As with her garden, Meg always took great care of the people closest to her. She enveloped everyone with warmth and kindness and provided unconditional support to her family and friends.  She offered a patient and attentive ear and had an innate ability to set people at ease. In her quiet, humble, and selfless way, she helped all those around her become the best versions of themselves. Although it ended too soon, her life was full of love.</p>
<p>Meg is survived by her husband of 32 years Michael Patrick, her son William Patrick, her daughter Susan Patrick, her son-in-law Peter Muller, her sister Sue Parker, her brother Whit Kemper, and many loving family members. </p>
<p>Meg’s family would like to express their gratitude to the many friends, family, and neighbors who have provided support and care in the past six years.  They particularly want to thank Meg’s sister Sue, her sister-in-law Peggy Spain, and her dear friends Pam Bailey and Anne Mulkern. In lieu of flowers, her family would suggest memorial donations in Meg’s name to either of the following organization:</p>
<ul>
<li> <a href="http://ncbg.unc.edu/">North Carolina Botanical Gardens</a>, The University of North Carolina at Chapel Hill, Campus Box 3375, Chapel Hill, North Carolina 27599.</li>
<li><a href="http://ncbg.unc.edu/">The Orange County Rape Crisis Center</a>, P. O. Box 4722, Chapel Hill, NC 27515.</li>
</ul>
<p>Meg’s life will be celebrated in a private ceremony that will be scheduled in January.</p>

app/views/static_pages/guestbook.html.erb
<h1>Guestbook goes here</h1>
<p></p>